### ISSUE TITLE
Add blahaj

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/joy#4]
Need i say more

**Comment by tuopi27** [comment]
https://modrinth.com/mod/blahaj-of-undying

i have the perfect mod for you

**Comment by blryface** [comment]
Well since this is Unlicense, bipty bopty...

**Comment by blryface** [comment]
We can probably embed some blahaj fabric mod in Joy due to them being Unlicense

**Comment by blryface** [comment]
how have we not added this yet

**Comment by blryface** [comment]
completed in [these commits](https://github.com/Pridecraft-Studios/joy/compare/d152203a19ee...516110951dd6)
can't believe this took 10 months???

**Comment by blryface** [comment]
we should credit the original authors clearly when finishing up the release
