### ISSUE TITLE
[Suggestion] Marriage system

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/joy#8]
Suggested by callmeecho

A marriage system, not exclusively limited to queer marriages.

**Comment by blryface** [comment]
people can already do this with roleplay lol?

**Comment by blryface** [comment]
maybe we can add rings but does it directly fit a LGBT stuffs mod?

**Comment by Ampflower** [comment]
I would generally consider this out of scope

**Comment by worldwidepixel** [comment]
Out of scope
